package Project.AI.Format;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Class with fields contained in a response by the OpenAI API.
 * As this is generated by jackson from JSON I need to flag to ignore other fields
 * contained in the response but not in this class bcuz else jackson will throw.
 * **class inspired by gpt-4o**
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class OpenAIResponse {
    public List<Choice> choices;

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Choice {
        public OpenAIMessage message;
    }
}
