package Project.AI.Format;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * A Message with fields required by OpenAI API.
 * As this is generated by jackson from JSON I need to flag to ignore other fields
 * contained in the message but not in this class bcuz else jackson will throw.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class OpenAIMessage {
    public String role; //e.g. user, assistant (AI), system (systemprompt)
    public String content;

    public OpenAIMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }
    public OpenAIMessage() {}
}
