package Project.window.ThreeDPaneHandling;

import Project.SelectionModel.FXGroupDraw.HasFXGroupContents;
import Project.SelectionModel.FXGroupDraw.HasFXGroupContentsContainer;
import Project.SelectionModel.FXGroupSelection.HasFXGroupSelection;
import Project.command.DrawCommands.ColorMeshviewsCommand;
import Project.command.DrawCommands.ResetViewDrawCommand;
import Project.command.DrawCommands.SliceCommand;
import Project.window.Slicing.Plane;
import Project.window.ThreeDPaneHandling.Effects.SelectionEffect;
import Project.window.ThreeDPaneHandling.Movement.CamMover;
import Project.window.ThreeDPaneHandling.Movement.Group3DRotation;
import Project.window.ThreeDPaneHandling.Movement.MouseScrolling3D;
import Project.window.ThreeDPaneHandling.Movement.SetupMouseRotate3D;
import Project.window.ThreeDPaneHandling.Objects.Arrow;
import javafx.beans.InvalidationListener;
import javafx.collections.ListChangeListener;
import javafx.concurrent.Task;
import javafx.geometry.Bounds;
import javafx.geometry.Point3D;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.PerspectiveCamera;
import javafx.scene.input.KeyCode;
import javafx.scene.input.PickResult;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Box;
import javafx.scene.shape.MeshView;
import javafx.scene.transform.Affine;
import javafx.scene.transform.Transform;

import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import java.util.logging.Level;
import java.util.logging.Logger;

import static Project.window.WindowPresenter.centerGroupToItself;

public class ThreeDGroupHandler {

    private static final Logger logger = Logger.getLogger(ThreeDGroupHandler.class.getName());

    private final String handlerID;

    private final Pane pane;
    private final PerspectiveCamera perspectiveCamera;//  = new PerspectiveCamera(true); //camera in 3D view
    public static Point3D DEFAULT_INITIAL_CAMERA_POSITION = new Point3D(0,-10,-1800);

    private static final Affine INITIAL_TRANSFORM = new Affine( //initial transform of the group holding the 3D contents. serves as reset position
            1.0, 0.0, 0.0, 0.0,
            0.0, 0.0, -1.0, 0.0,
            0.0, 1.0, 0.0, 0.0
    );

    // these two doubles decide how large each step of zoom (via scrolling) or rotation is
    private static final double zoomStep = 4;
    private static final double rotationStep = 2;

    private final Group root3d;         //root group of the 3d view holding the groups below.
    private final Group slicePlaneGroup;//will hold plane for slicing meshes
    private final Group contentGroup;   //holds the innerGroup
    private final Group innerGroup;     //holds the meshViews

    private final HasFXGroupContents hasFXGroupContents;
    private final HasFXGroupContentsContainer hasFXGroupContentsContainer;
    private final HasFXGroupSelection hasFXGroupSelection;

    private boolean clickSelectable = true; // toggle whether the user can select MeshViews via mouse click. enabled by default

    private final CamMover camMover; // controls camera movement
    private final Group3DRotation contentGroupRotator;      // implements rotation of the 3D view via rotation of a group
    private final Group3DRotation slicePlaneGroupRotator;   // rotates the slicing plane
    private final SetupMouseRotate3D setupMouseRotate3D;    // uses groupRotater to rotate a group using mouse drag
    private boolean isRotating = false; //is the user rotating the 3D view via mouse drag right now? if so, disable click-selecting meshViews

    /** The currently chosen selection effect */
    private SelectionEffect.Effect selectionEffect = SelectionEffect.Effect.VIA_SATURATION;

    /** A function that handles tasks generated by this class. By default, this does nothing else other than call task.run().*/
    private Function<Task<?>, ?> handleTask = (Function<Task<?>, Object>) task -> {
        task.run();
        return null;
    };


    public SelectionEffect.Effect getSelectionEffect() {
        return this.selectionEffect;
    }

    public void setSelectionEffect(SelectionEffect.Effect selectionEffect) {
        this.selectionEffect = selectionEffect;
    }

    public HasFXGroupContents getHasFXGroupContents() {
        return this.hasFXGroupContents;
    }

    public HasFXGroupContentsContainer getHasFXGroupContentsContainer () {
        return this.hasFXGroupContentsContainer;
    }

    public HasFXGroupSelection getHasFXGroupSelection() {
        return this.hasFXGroupSelection;
    }

    /**
     * Set a function to handle the Task of loading OBJ files. For example to put it on a new Thread or to bind UI to the task.<P>
     *     If set, this class WILL NOT run() the task anymore! This must be done by the provided function.
     * <P>
     *     The task updates progress and has a message.
     * @param handleLoadingTask a function that accepts the task. Set to null to make this class run tasks again itself (not on a new Thread).
     */
    public void setHandleLoadingTask(Function<Task<?>, ?> handleLoadingTask) {
        this.handleTask = handleLoadingTask;
    }


    /**
     * Creates a slice plane at a MeshView. The MeshView must be currently drawn.
     * @param meshViewID ID of a MeshView of HasFXGroupContents.
     * @param positive looking in direction of the axis is looking at the cut. means if positive, the stuff further away will be kept and the stuff closeby cut away.
     */
    public void createSlicePlaneAtMeshView(String meshViewID, Plane.BodyAxis bodyAxis, boolean positive) {
        Point3D rotateAxis = null;
        double rotateAngle = 0;

        switch (bodyAxis) {
            case CORONAL -> {
                rotateAxis = new Point3D(1,0,0); rotateAngle = (positive ? 90 : 270);
            }
            case AXIAL -> {
                rotateAxis = new Point3D(1,0,0); rotateAngle = (positive ? 0 : 180);
            }
            case SAGGITAL -> {
                rotateAxis = new Point3D(0,1,0); rotateAngle = (positive ? 90 : 270);
            }
        }

        logger.log(Level.CONFIG, "Setting slice plane at meshview: " + meshViewID);
        MeshView meshView = hasFXGroupContents.getMeshViewWithID(meshViewID);
        if (meshView == null || !hasFXGroupContents.getSelection().contains(meshView)) {
            logger.log(Level.CONFIG, "invalid meshViewID: " + meshViewID + ". Aborting");
            return; //can only cut Meshviews that this 3DHandler has and that are drawn
        }

        setupSlicePlane();

        for (Node node : slicePlaneGroup.getChildren()) node.getTransforms().clear();   // see notes

        Point3D meshViewSceneCenter = meshView.localToScene(Plane.computeCenter(meshView));

        Point3D boxLocalCenter = slicePlaneGroup.getChildren().getFirst().sceneToLocal(meshViewSceneCenter);

        for (Node node : slicePlaneGroup.getChildren()) {
            Group3DRotation.applyTranslate(node, boxLocalCenter);
            Group3DRotation.applyGlobalRotation(node,rotateAxis, rotateAngle);
        }

        switch (bodyAxis) { // so that red and green side are not inside each other
            case CORONAL -> {
                slicePlaneGroup.getChildren().getFirst().setTranslateY(1);
            }
            case AXIAL -> {
                slicePlaneGroup.getChildren().getFirst().setTranslateZ(1);
            }
            case SAGGITAL -> {
                slicePlaneGroup.getChildren().getFirst().setTranslateX(1);
            }
        }

    }


    /**
     * Slices the given MeshViews with the existing slice plane. Has NO EFFECT if no slice plane exists.
     * @param meshViews MeshViews to be sliced
     */
    public void slice(List<MeshView> meshViews) {
        if (meshViews.isEmpty()) meshViews = hasFXGroupContents.getAllItems();
        SliceCommand sliceCommand = new SliceCommand(meshViews, innerGroup, (Box) slicePlaneGroup.getChildren().getFirst(), hasFXGroupContents, hasFXGroupSelection);
        sliceCommand.setHandleSlicingTask(task -> {handleTask.apply(task); return null;});
        sliceCommand.execute(); //for now, commands are not remembered.
        slicePlaneGroup.getChildren().clear();
        hasFXGroupSelection.clearSelection();
    }

    /**
     * Rotates the 3D view.
     */
    public void applyGlobalRotation(Point3D axis, double angle) {
        Group3DRotation.applyGlobalRotation(contentGroup, axis, angle, setupMouseRotate3D.getPivot());
        Group3DRotation.applyGlobalRotation(slicePlaneGroup, axis, angle, setupMouseRotate3D.getPivot());
    }


    /**
     * Shifts the field of view so that the target is approximately in the middle.
     * Does NOT rotate the view.
     * @param meshView
     */
    public void viewToMeshView(MeshView meshView) {
        Bounds meshViewBounds = meshView.localToScene(meshView.getBoundsInParent());

        Point3D step = new Point3D(-meshViewBounds.getCenterX(), -meshViewBounds.getCenterY(), -meshViewBounds.getCenterZ());

        Group3DRotation.applyTranslate(contentGroup, step);
        Group3DRotation.applyTranslate(slicePlaneGroup, step);
    }

    /**
     * Create an arrow and point it at a target.
     * @param target target to point at
     * @param bodyAxis body axis in which the arrow lies
     * @param positive is the arrow pointing in positive direction of the coordinate system axis?
     * @param dontPierce if true, dont let the tip of the arrow point at the center of the target but at the outer bound
     * @param color color of the arrow
     */
    public Arrow pointArrowAt(MeshView target, Plane.BodyAxis bodyAxis, boolean positive, boolean dontPierce, Color color) {
        Bounds groupBounds = innerGroup.getBoundsInLocal();
        Bounds targetBounds = target.getBoundsInLocal();
        double length = 0;

        switch (bodyAxis) {
            case AXIAL -> {
                length = positive ? targetBounds.getCenterZ() - groupBounds.getMinZ(): groupBounds.getMaxZ() - targetBounds.getCenterZ();
            }
            case SAGGITAL -> {
                length = positive ? targetBounds.getCenterX() - groupBounds.getMinX(): groupBounds.getMaxX() - targetBounds.getCenterX();
            }
            case CORONAL -> {
                length = positive ? targetBounds.getCenterY() - groupBounds.getMinY(): groupBounds.getMaxY() - targetBounds.getCenterY();
            }
        }

        length *= 1.3;
        Arrow arrow = new Arrow(length, color);
        arrow.pointAt(target, innerGroup, bodyAxis, positive, dontPierce);
        return arrow;
    }

    /**
     * Removes the arrow from view.
     */
    public void removeArrow(Arrow arrow) {
        innerGroup.getChildren().remove(arrow);
    }

    /**
     * Convenience method that resets the TriangleMeshes of all currently drawn MeshViews back to default.
     */
    public void defaultMeshes() {
        for (MeshView meshView : hasFXGroupContents.getSelection()) hasFXGroupContents.resetTriangleMesh(meshView.getId());
    }


    public ThreeDGroupHandler(Pane pane, PerspectiveCamera camera, Point3D initialCameraPosition, String id) {
        this.handlerID = id;
        this.pane = pane;
        this.perspectiveCamera = camera;
        this.camMover = new CamMover(perspectiveCamera);

        //initialize the contentGroup via Setup3DSubPane
        LinkedList<Group> outerGroups = Setup3DSubPane.setup3DSubPane(this.pane, camera, initialCameraPosition);
        root3d = outerGroups.get(0);    // root3d holds contentGroup.
        // If you want to add more content that is independet from the meshes (i.e. independent from innerGroup),
        // add a new group to root3d and put it in there. like for example the slice pane.
        // It will not be affected by clearing the view or any rotation, mouse drag etc unless you add that group to
        // specific methods (like SetupMouseRotate3D).
        slicePlaneGroup = new Group();
        root3d.getChildren().add(this.slicePlaneGroup);
        contentGroup = outerGroups.get(1);
        this.innerGroup = new Group();


        // Rotation
        this.contentGroupRotator = new Group3DRotation(contentGroup);
        this.slicePlaneGroupRotator = new Group3DRotation(slicePlaneGroup);
        setupMouseRotate3D = new SetupMouseRotate3D(this.pane, new Group[]{contentGroup, slicePlaneGroup});

        //mouse scrolling functionality
        MouseScrolling3D mouseScrolling3D = new MouseScrolling3D(new Group3DRotation[] {contentGroupRotator, slicePlaneGroupRotator},this.pane);


        contentGroup.getChildren().add(innerGroup);
        contentGroup.getTransforms().setAll(INITIAL_TRANSFORM);



        //--------------------------3D draw model-------------------
        this.hasFXGroupContents = new HasFXGroupContents(innerGroup, id + "hasFXContents");
        this.hasFXGroupContentsContainer = new HasFXGroupContentsContainer(hasFXGroupContents); //, new String[]{isAFilesLocation.getValue().getAbsolutePath(), partOfFilesLocation.getValue().getAbsolutePath()}
        this.hasFXGroupContents.setHasFXGroupContentsContainer(hasFXGroupContentsContainer);
        //---------------------------


        //---------------initialize 3D selection model-----------
        hasFXGroupSelection = new HasFXGroupSelection(hasFXGroupContents, id + "hasFXSelection");
        //-----------------------------------------------

        hasFXGroupContents.getSelection().addListener((InvalidationListener) e -> centerGroupToItself(innerGroup));  //should be called after the command below, otherwise it'll fire every loop

        //---------------implement 3D mouse selection------------------
        innerGroup.setOnMouseReleased(event -> {
            if (isRotating) {
                isRotating = false; //dont de-/select when you were just mouse dragging for rotating
                return;
            }
            if (clickSelectable) {
                PickResult result = event.getPickResult();
                Node pickedNode = result.getIntersectedNode();
                if (pickedNode instanceof MeshView mesh) {
                    if (!hasFXGroupSelection.getSelection().contains(mesh)) {
                        hasFXGroupSelection.select(mesh);
                    } else {
                        hasFXGroupSelection.unselect(mesh);
                    }
                }
            }
        });
        innerGroup.setOnMouseDragged(event -> isRotating = true); //user is currently rotating ;)
        //---------------------------------------------

        //------------Call change of appearance of MeshViews upon un-/selecting them------------
        hasFXGroupSelection.getSelection().addListener((ListChangeListener<MeshView>) c -> {
            while (c.next()) {
                if (c.wasAdded()) {
                    for (MeshView node : c.getAddedSubList()) {
                        if (node != null) {
                            meshViewSelectionEffect(node, true);

                        }
                    }
                }
                if (c.wasRemoved()) {
                    for (MeshView node : c.getRemoved()) {
                        if (node != null) {
                            meshViewSelectionEffect(node, false);
                        }
                    }
                }
            }
        });
        //---------------------------------------------------

    }

    /**
     * Apply the 3D selection effect.
     * @param meshView to select.
     * @param selected: to select or to unselect (decides which effect is applied).
     */
    private void meshViewSelectionEffect(MeshView meshView, boolean selected) {
        SelectionEffect.applySelectionEffect(meshView, selected, selectionEffect);
    }

    /**
     * Change the selectionEffect of this to the newEffect. Then apply the new effect on all MeshViews of threeDContentGroup.
     * @param newEffect the new effect
     */
    public void changeSelectionEffect(SelectionEffect.Effect newEffect) {
        for (MeshView meshView : hasFXGroupContents.getAllItems()) {
            boolean isSelected = hasFXGroupSelection.getSelection().contains(meshView);
            SelectionEffect.transformSelectionMode(meshView, isSelected, this.selectionEffect, newEffect);
        }
        this.selectionEffect = newEffect;
    }


    public void resetView() {
        new ResetViewDrawCommand(new Group[]{contentGroup, slicePlaneGroup},perspectiveCamera, INITIAL_TRANSFORM, DEFAULT_INITIAL_CAMERA_POSITION, setupMouseRotate3D).execute();
    }

    /**
     * Resets color to default for all MeshViews, drawn and undrawn.
     */
    public void resetColors() {
        for (MeshView meshView : getHasFXGroupContents().getAllItems()) {
            new ColorMeshviewsCommand(hasFXGroupContents.getDefaultColorForID(meshView.getId()), Set.of(meshView.getId()), hasFXGroupContents, hasFXGroupSelection).execute();
        }
    }

    /**
     * Does:
     * <ul>
     *     <li>reset colors</li>
     *     <li>reset perspective</li>
     *     <li>undraws the slice plane</li>
     * </ul>
     * Does NOT:
     * <ul>
     *     <li>change which MeshViews are drawn</li>
     *     <li>change the TriangleMeshes of MeshViews</li>
     * </ul>
     */
    public void softViewReset() {
        slicePlaneGroup.getChildren().clear();
        resetView();
        resetColors();
        changeSelectionEffect(SelectionEffect.Effect.VIA_SATURATION);
    }

    public void hardViewReset() {
        hasFXGroupContents.clearSelection();
        hasFXGroupSelection.clearSelection();
        slicePlaneGroup.getChildren().clear();
        innerGroup.getChildren().removeIf(node -> node instanceof Arrow);
        softViewReset();
    }


    /**
     * @return can the user select MeshViews via mouse click?
     */
    public boolean isClickSelectable() {return clickSelectable;}

    /**
     * @param clickSelectable true -> the user can select MeshViews via mouse click. false -> they cannot.
     */
    public void setClickSelectable(boolean clickSelectable) {this.clickSelectable = clickSelectable;}


    /**
     * <li>Creates the slice plane according to the size of innergroup.</li>
     * <li>By default, the slice plane spawns in the middle of contentgroup.</li>
     * <li>Sets the maximum allowed distance the slice plane and the contentgroup are allowed to move,
     * making sure that they always overlap.</li>
     */
    private void setupSlicePlane() {
        if (hasFXGroupContents.getSelection().isEmpty()) {
            return;
        }
        slicePlaneGroup.getChildren().clear();
        double planeSize = Math.max(Math.max(innerGroup.getBoundsInLocal().getMaxX() - innerGroup.getBoundsInLocal().getMinX(), innerGroup.getBoundsInLocal().getMaxY() - innerGroup.getBoundsInLocal().getMinY()), innerGroup.getBoundsInLocal().getMaxZ() - innerGroup.getBoundsInLocal().getMinZ()) * 2;
        Group slicePlane = Plane.makeSlicePlane((int) planeSize);
        slicePlaneGroupRotator.setIsTransformForbidden(new Function<>() {
            @Override
            public Boolean apply(Transform transform) {
                Transform conTrans = contentGroup.getTransforms().getFirst();
                Point3D diff = new Point3D(Math.abs(transform.getTx() - conTrans.getTx()), Math.abs(transform.getTy() - conTrans.getTy()), Math.abs(transform.getTz() - conTrans.getTz()));
                return diff.getX() >= planeSize / 4 || diff.getY() >= planeSize / 4 || diff.getZ() >= planeSize / 4;
            }
        });
        contentGroupRotator.setIsTransformForbidden(new Function<>() {
            @Override
            public Boolean apply(Transform transform) {
                Transform conTrans = slicePlaneGroup.getTransforms().getFirst();
                Point3D diff = new Point3D(Math.abs(transform.getTx() - conTrans.getTx()), Math.abs(transform.getTy() - conTrans.getTy()), Math.abs(transform.getTz() - conTrans.getTz()));
                return diff.getX() >= planeSize / 4 || diff.getY() >= planeSize / 4 || diff.getZ() >= planeSize / 4;
            }
        });
        slicePlaneGroup.getTransforms().setAll(contentGroup.getTransforms().getFirst());    //setting the transfrom so that the plane spawns in the middle of the contentgroup
        slicePlaneGroup.getChildren().addAll(slicePlane.getChildren());
        slicePlaneGroup.setVisible(true);
    }


    /**
     * Rotates/Translates 3D objects depending on the keycode and boolean.
     * @param keyCode controls the direction
     * @param rotating false -> the camera is moved. true -> the objects are rotated
     * @param shift If shift is pressed, move the slice plane.
     */
    public void rotationControl(KeyCode keyCode, boolean rotating, boolean shift) {
        Group3DRotation groupRotator = shift ? slicePlaneGroupRotator : contentGroupRotator;

        if (keyCode == KeyCode.LEFT) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(-zoomStep, 0, 0));
            else groupRotator.applyGlobalRotation(new Point3D(0, 1, 0), rotationStep);

        } else if (keyCode == KeyCode.RIGHT) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(zoomStep, 0,0));
            else groupRotator.applyGlobalRotation(new Point3D(0,1, 0), -rotationStep);

        } else if (keyCode == KeyCode.UP) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(0, -zoomStep, 0));
            else groupRotator.applyGlobalRotation(new Point3D(1, 0, 0), -rotationStep);

        } else if (keyCode == KeyCode.DOWN) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(0, zoomStep, 0));
            else groupRotator.applyGlobalRotation(new Point3D(1,0,0), rotationStep);

        } else if (keyCode == KeyCode.PLUS) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(0 ,0 , -zoomStep));
            else groupRotator.applyGlobalRotation(new Point3D(0,0,1), rotationStep);
        }
        else if (keyCode == KeyCode.MINUS) {
            if (!rotating) groupRotator.applyTranslate(new Point3D(0,0,zoomStep));
            else groupRotator.applyGlobalRotation(new Point3D(0,0,1), -rotationStep);
        }
    }

}

