package Project.Util;

public record Lorem() {
    public static final String LOREM = """
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus ultrices velit sit amet luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Suspendisse in placerat ex, eu feugiat quam. Praesent ac ultrices nunc. Proin finibus, ligula ut pretium vulputate, arcu mauris laoreet orci, eu faucibus arcu erat id libero. Aenean sapien ipsum, tempor at lorem id, placerat rhoncus eros. Vivamus pharetra vitae velit id tincidunt. Donec porttitor libero vitae justo accumsan viverra. Mauris luctus feugiat ex ut eleifend. Proin vel neque id odio tristique varius non quis felis. Nunc vitae elit id diam maximus ullamcorper. Nam vestibulum sapien ut convallis maximus. Etiam eleifend lorem et erat tincidunt, bibendum suscipit purus volutpat.
            
            Curabitur laoreet malesuada tortor, vel mattis dui volutpat sit amet. Pellentesque ipsum tellus, aliquam eget lobortis quis, vehicula sit amet ante. Pellentesque massa nisl, hendrerit id massa sit amet, tincidunt hendrerit enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed molestie lacinia libero, id ultrices libero viverra et. Duis faucibus sit amet ex ac placerat. Vestibulum commodo nunc lorem, non bibendum libero ultricies ac. Integer nisl risus, feugiat eget pulvinar at, mattis vitae leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum iaculis nisi ac consequat vehicula. Nunc et magna dui. Aliquam eget ipsum sit amet mi posuere facilisis.
            
            Integer sed laoreet est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nulla ipsum, suscipit ac metus eu, condimentum vulputate enim. Nulla a ipsum sed tortor efficitur fringilla. Cras pellentesque lacinia condimentum. Integer posuere, ligula et rhoncus dictum, elit velit ultrices massa, non aliquam augue sapien at turpis. Mauris non blandit mi. Donec aliquam eget sem id tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque faucibus vulputate lorem id posuere. Cras in leo id arcu pretium lacinia eu porttitor nunc. Suspendisse a nulla malesuada, venenatis ipsum quis, blandit nulla. Mauris enim libero, maximus a aliquam sit amet, accumsan eu eros.
            
            Nam eget leo ut tellus egestas blandit. Donec a mauris vitae tellus consequat tempor. Aenean accumsan laoreet vulputate. Aliquam erat volutpat. Etiam ac pulvinar ante, iaculis tincidunt ante. Donec volutpat efficitur imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus a rhoncus neque. Vestibulum eu felis lacinia, gravida metus quis, malesuada felis. Integer venenatis erat sed eleifend lobortis. Integer euismod molestie tellus vitae molestie. Nunc blandit nisi et turpis rutrum aliquam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at augue lectus. Nunc ultricies tortor ac diam facilisis, sed gravida nibh suscipit. Praesent tellus urna, faucibus at iaculis vitae, pulvinar quis nulla.
            
            Nulla ac lectus nulla. Morbi suscipit augue at dui viverra, ut condimentum massa faucibus. Pellentesque sit amet ex egestas, vulputate nisl sed, ornare neque. Etiam venenatis felis nec magna faucibus, ac porta nisi hendrerit. Nunc in arcu nunc. Morbi vehicula quam ut felis accumsan tristique. Aenean pellentesque auctor porttitor. Donec porttitor et ex sit amet tincidunt. Suspendisse rhoncus mauris odio, et interdum augue pulvinar non. Fusce laoreet, nunc et placerat aliquam, lacus lacus malesuada leo, sed tempus ligula turpis vel ex. Aliquam ultrices est eget metus gravida, vitae ultricies lacus eleifend. Curabitur quis augue risus. Duis sagittis magna sed lorem gravida, a egestas ligula fringilla. Mauris nec ultrices quam, non sagittis sapien. Suspendisse eget orci vitae nibh feugiat rhoncus. Proin eget rhoncus nibh.
            """;
}
